### ISSUE TITLE
Why not all the KEEL algo ? 

### ISSUE THREAD

**Issue by martiniscovici** [i02momuj/RKEEL#4]

**Comment by i02momuj** [comment]
The number of algorithms in KEEL is so large that just a subset of them was included in RKEEL. However, in the [original RKEEL paper](https://doi.org/10.1109/fuzz-ieee.2016.7737695), in last section it is explained how to extend RKEEL to include other KEEL algorithms that were not previously included. 
It is very easy to include a new KEEL algorithm following these instructions, and you can contact me if you have any issue with it.
